services:
  polybot:
    image: ${POLYBOT_IMG_NAME}
    ports:
      - "8443:8443"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_APP_URL=${TELEGRAM_APP_URL}
      - BUCKET_NAME=${BUCKET_NAME}
    networks:
      - mongoCluster
    volumes:
      - /home/mohammadgh/.aws/credentials:/root/.aws/credentials

  yolo:
    image: ${YOLO_IMG_NAME}
    ports:
      - "8081:8081"
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
    networks:
      - mongoCluster
    volumes:
      - /home/mohammadgh/.aws/credentials:/root/.aws/credentials

  mongo1:
    image: mongo:5
    container_name: mongo1
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongoCluster

  mongo2:
    image: mongo:5
    container_name: mongo2
    restart: always
    ports:
      - "27018:27017"
    networks:
      - mongoCluster

  mongo3:
    image: mongo:5
    container_name: mongo3
    restart: always
    ports:
      - "27019:27017"
    networks:
      - mongoCluster


